### ISSUE TITLE
Ready to merge

### ISSUE THREAD

**Issue by yassinphilip** [rukano/emacs-faust-mode#4]
Alright, I think I'm done, it was really easier/faster than I though it would be : Now, (at least on this machine :)) [Faustine depends on Faust-mode](https://bitbucket.org/yassinphilip/faustine/src/f3e37bb287c7d2bca5f61551d6f478cfcbbf0cf3/faustine.el?at=ext-mode&fileviewer=file-view-default), and is now empty of all "syntax" directives, [everything is now in Faust-mode](https://github.com/rukano/emacs-faust-mode/blob/refactoring/faust-mode.el).

Now, I'm going to [see with the MELPA team](https://github.com/melpa/melpa/issues/4981) that everything goes smoothly. 929 (wow) people have installed Faust-mode from MELPA, nothing bad should happen to them, right? Ideally, they'll just end up with a better mode when updating. For Faustine users, it should be a little more complicated, as Faust-mode should be automatically installed as well when they update, all 10 of them :)

All in all, I'm really happy with this neat, clean, and to-the-point combination : A really comprehensive (and self-contained, a proper *mode*) Faust-mode, and a powerful IDE-like library of commands that makes good use of it.

What do you say?

**Comment by rukano** [comment]
Sounds good!
I started the faust mode years ago and was only for some quick coding, didn't knew it would be this kind of big. So I'm happy you get to refactor and fix some stuff. Although I haven't been using FAUST in the last years, I guess we have some stuff in common :)

I didn't even knew faust-mode was in ELPA... :D somebody might have suggested it, and since it was small and quick to review they probably added it to the packages ^_^
